language: python
python:
  - 2.7
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  - PLONE_VERSION=4.3 QA=true
  - PLONE_VERSION=5.0
matrix:
  allow_failures:
    - env: PLONE_VERSION=5.0
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - sed -ie "s#plone-4.3.x.cfg#plone-$PLONE_VERSION.x.cfg#" travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test-coverage --all
after_success:
  - pip install coveralls
  - coveralls
notifications:
  email:
    - tisto@plone.org
    - jens@bluedynamics.com

