language: python
python:
  - 2.7
cache:
  pip: true
  directories:
    - buildout-cache
env:
  - PLONE_VERSION=4.3 QA=true
  - PLONE_VERSION=5.0
matrix:
  allow_failures:
    - env: PLONE_VERSION=5.0
before_install:
  - pip install zc.buildout
  - mkdir -p buildout-cache/{eggs,downloads}
install:
  - sed -ie "s#plone-4.3.x.cfg#plone-$PLONE_VERSION.x.cfg#" travis.cfg
  - buildout -Nc travis.cfg annotate
  - buildout -Nc travis.cfg
script:
  - bin/code-analysis
  - bin/test-coverage
after_success:
  - pip install coveralls
  - coveralls
notifications:
  email:
    - tisto@plone.org

