[tool.black]
line-length = 88
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.github
    | \.eggs
    | \.git
    | \bin
    | \docs
    | \lib
    | \lib64
    | \parts
  )/
)
'''

[tool.isort]
force_alphabetical_sort=true
force_single_line=true
lines_after_imports=2
line_length=88
